### ISSUE TITLE
comma separation

### ISSUE THREAD

**Issue by pentarex** [doowb/parse-mentions#1]
hey, ive tried the library, but the first test I've did it failed. I am not sure if this should work but the test case is: 
```javascript 
var mentions = parse("This is cool library @user1, @user2");
console.log(mentions);
//=> ['user2']
```
The issue is in the comma, not sure if a lot of people are using mentions with comma separation, but thought will be good to let you know :)

**Comment by doowb** [comment]
Thanks! The regex for getting the mentions is probably wrong. If you'd like to take a shot at fixing it through a PR that'd be awesome. Otherwise, I'll try to get to it when I work on this next.
